# Clippy configuration for EfSec WASM
# Enforces Rust best practices and catches common mistakes

# Cognitive complexity limits
cognitive-complexity-threshold = 30

# Type complexity limits  
type-complexity-threshold = 250

# Avoid false positives for WASM bindings
avoid-breaking-exported-api = true

# Enable pedantic lints for high code quality
# Note: These are enabled via command line in CI: -W clippy::pedantic