# Rust formatting configuration for EfSec WASM
# Ensures consistent code style across the project

# Edition
edition = "2021"

# Basic formatting
max_width = 100
hard_tabs = false
tab_spaces = 4

# Imports
imports_granularity = "Crate"
reorder_imports = true
group_imports = "StdExternalCrate"

# Functions
fn_single_line = false
fn_args_layout = "Tall"
brace_style = "SameLineWhere"

# Control flow
control_brace_style = "AlwaysSameLine"
match_block_trailing_comma = true

# Comments and documentation
wrap_comments = true
normalize_comments = true
normalize_doc_attributes = true

# Strings and formatting
format_strings = true
format_macro_matchers = true

# Misc
trailing_semicolon = true
trailing_comma = "Vertical"
space_before_colon = false
space_after_colon = true