# Copyright (C) 2025 efchat.net
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Setup wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@efchatnet'

      - name: Extract version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Update package version
        run: |
          cd client
          npm version ${{ steps.version.outputs.VERSION }} --no-git-tag-version
          echo "Updated package.json to version ${{ steps.version.outputs.VERSION }}"

      - name: Build WASM + TypeScript
        run: |
          make verify
          make build-all

      - name: Run tests
        run: make test-all

      - name: Publish to GitHub Packages
        run: |
          cd client
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: "EfSec v${{ steps.version.outputs.VERSION }}"
          body: |
            ## EfSec E2E Encryption Library v${{ steps.version.outputs.VERSION }}
            
            ### 🔒 Features
            - Double Ratchet (Signal Protocol) for 1:1 messaging
            - Megolm protocol for group messaging  
            - WebAssembly implementation using audited vodozemac
            - Zero-knowledge client-side encryption
            - Browser-compatible (Firefox, Chrome, Safari, etc.)
            
            ### 📦 Installation
            ```bash
            npm install @efchatnet/efsec@${{ steps.version.outputs.VERSION }}
            ```
            
            ### 🛡️ Security
            Built on Matrix's [vodozemac](https://github.com/matrix-org/vodozemac) library, audited by Least Authority.
            
            ### 📚 Documentation
            See [README.md](https://github.com/efchatnet/efsec/blob/main/README.md) for complete usage documentation.
          files: |
            efsec-wasm/pkg/*.wasm
            efsec-wasm/pkg/*.js
            efsec-wasm/pkg/package.json
            client/dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}